version: "3.3"

services:
  mysql:
    image: mysql
    container_name: mysql-pi
    restart: always
    ports:
      - 3306:3306
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=gobarber
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  mongobd:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/mongo

  app:
    build: .
    container_name: gobarber
    restart: always
    ports:
      - 3335:3335
    volumes:
      - .:/usr/app
    links:
      - mysql
      - mongobd
    depends_on:
      - mysql
      - mongobd



volumes:
  db-config:
    driver: local
  db-data:
    driver: local
  mongodata:
    driver: local
